export const productCategories = [
  {
    id: "wall-hooks",
    name: "Wall Hooks",
    description: "Elegant wall hooks for every space — entryways, bathrooms, kitchens",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80&fit=crop",
    count: "15+ Products",
    icon: "🪝",
  },
  {
    id: "home-accessories",
    name: "Home Accessories",
    description: "Premium home accessories that blend style with everyday utility",
    image: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=600&q=80&fit=crop",
    count: "20+ Products",
    icon: "🏠",
  },
  {
    id: "bathroom-shelf",
    name: "Bathroom Shelf",
    description: "Smart bathroom shelving solutions — stainless steel and chrome finish",
    image: "https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=600&q=80&fit=crop",
    count: "12+ Products",
    icon: "🗄",
  },
  {
    id: "toilet-paper-holder",
    name: "Toilet Paper Holder",
    description: "Sleek and durable toilet paper holders in various premium finishes",
    image: "https://images.unsplash.com/photo-1564540574859-0dfb63985953?w=600&q=80&fit=crop",
    count: "10+ Products",
    icon: "🧻",
  },
  {
    id: "toothbrush-holder",
    name: "Toothbrush Holder",
    description: "Hygienic and stylish toothbrush holders for modern bathrooms",
    image: "https://images.unsplash.com/photo-1607613009820-a29f7bb81c04?w=600&q=80&fit=crop",
    count: "8+ Products",
    icon: "🪥",
  },
  {
    id: "health-faucet",
    name: "Health Faucet",
    description: "High-pressure health faucets with ergonomic design",
    image: "https://images.unsplash.com/photo-1588854337221-4cf9fa96059c?w=600&q=80&fit=crop",
    count: "18+ Products",
    icon: "🚿",
  },
  {
    id: "shower-head",
    name: "Shower Head",
    description: "Rain shower heads and multi-function shower systems",
    image: "https://images.unsplash.com/photo-1631049552240-59c37f38802b?w=600&q=80&fit=crop",
    count: "22+ Products",
    icon: "🚿",
  },
  {
    id: "kitchen-accessories",
    name: "Kitchen Accessories",
    description: "Functional kitchen accessories for organised, beautiful kitchens",
    image: "https://images.unsplash.com/photo-1766686039986-ca29c580ef3e?w=600&q=80&fit=crop",
    count: "16+ Products",
    icon: "🍳",
  },
  {
    id: "towel-accessories",
    name: "Towel Accessories",
    description: "Towel bars, rings, and holders in premium stainless steel",
    image: "https://images.unsplash.com/photo-1761353854312-a5df7c9d3bf5?w=600&q=80&fit=crop",
    count: "14+ Products",
    icon: "🛁",
  },
  {
    id: "soap-dish",
    name: "Soap Dish",
    description: "Elegant soap dishes and dispensers for bath and kitchen",
    image: "https://images.unsplash.com/photo-1567110684145-43024ecf0fa7?w=600&q=80&fit=crop",
    count: "10+ Products",
    icon: "🧼",
  },
  {
    id: "shower-arm",
    name: "Shower Arm",
    description: "Adjustable shower arms in chrome and brushed nickel finishes",
    image: "https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?w=600&q=80&fit=crop",
    count: "8+ Products",
    icon: "🔧",
  },
  {
    id: "telephone-shower",
    name: "Telephone Shower",
    description: "Hand showers with flexible hose — comfort and style combined",
    image: "https://images.unsplash.com/photo-1761353855019-05f2f3ed9c43?w=600&q=80&fit=crop",
    count: "12+ Products",
    icon: "📞",
  },
  {
    id: "bathroom-accessories",
    name: "Bathroom Accessories",
    description: "Complete bathroom accessory sets for a cohesive, premium look",
    image: "https://images.unsplash.com/photo-1507089947368-19c1da9775ae?w=600&q=80&fit=crop",
    count: "30+ Products",
    icon: "✨",
  },
  {
    id: "faucets",
    name: "Faucets",
    description: "Single-lever and dual-handle faucets for bath and kitchen",
    image: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=600&q=80&fit=crop",
    count: "25+ Products",
    icon: "🚰",
  },
  {
    id: "rbc-mirrors",
    name: "RBC Mirrors",
    description: "Exclusive RBC-branded mirrors — framed and frameless designs",
    image: "https://images.unsplash.com/photo-1576698483491-8c43f0862543?w=600&q=80&fit=crop",
    count: "10+ Products",
    icon: "🪞",
  },
  {
    id: "mirrors",
    name: "Mirrors",
    description: "Bathroom and full-length mirrors with premium frames",
    image: "https://images.unsplash.com/photo-1595455967759-5f1356993e53?w=600&q=80&fit=crop",
    count: "15+ Products",
    icon: "🪞",
  },
];

export const brands = [
  {
    id: "jaquar",
    name: "Jaquar",
    tagline: "World of Bath",
    description: "India's leading manufacturer of premium bathroom fittings, sanitaryware, and lighting solutions since 1960.",
    origin: "India",
    speciality: "Bathroom Fittings & Sanitaryware",
    color: "#1a2744",
  },
  {
    id: "essco-jaquar",
    name: "Essco Jaquar",
    tagline: "Quality at Scale",
    description: "Jaquar's value brand bringing reliable, stylish bathroom accessories to every Indian home.",
    origin: "India",
    speciality: "Affordable Bathroom Solutions",
    color: "#243252",
  },
  {
    id: "prince",
    name: "Prince",
    tagline: "Built to Last",
    description: "Trusted brand offering robust plastic and polymer bathroom accessories across India.",
    origin: "India",
    speciality: "Polymer Bathroom Fittings",
    color: "#c8a96e",
  },
  {
    id: "sintex",
    name: "Sintex",
    tagline: "Strength in Every Drop",
    description: "India's iconic brand known for water storage tanks, specialising in durable plastic solutions.",
    origin: "India",
    speciality: "Water Storage & Plastic Fittings",
    color: "#1a2744",
  },
  {
    id: "euroguard",
    name: "EuroGuard",
    tagline: "European Standards",
    description: "Bringing European design sensibility to Indian homes with premium bathroom accessories.",
    origin: "India",
    speciality: "Premium Hardware & Accessories",
    color: "#243252",
  },
  {
    id: "scud",
    name: "Scud",
    tagline: "Precision Engineered",
    description: "High-performance hardware accessories known for durability and precise engineering.",
    origin: "India",
    speciality: "Hardware & Fixtures",
    color: "#c8a96e",
  },
  {
    id: "racold",
    name: "Racold",
    tagline: "Warmth, Redefined",
    description: "Italy's Ariston Group brand — India's #1 water heater brand with 40+ years of legacy.",
    origin: "Italy / India",
    speciality: "Water Heaters & Geysers",
    color: "#e74c3c",
  },
  {
    id: "water-tec",
    name: "Water Tec",
    tagline: "Flow Forward",
    description: "Specialised water management and bathroom fitting solutions for modern construction.",
    origin: "India",
    speciality: "Water Management Systems",
    color: "#1a2744",
  },
  {
    id: "patton",
    name: "Patton",
    tagline: "Trusted Choice",
    description: "Reliable bathroom and home hardware brand known for quality and affordability.",
    origin: "India",
    speciality: "Home Hardware",
    color: "#243252",
  },
  {
    id: "mirrors-brand",
    name: "Mirrors",
    tagline: "Reflect Perfection",
    description: "Dedicated mirror brand offering a curated range of bathroom and decorative mirrors.",
    origin: "India",
    speciality: "Decorative & Functional Mirrors",
    color: "#8c9cb0",
  },
];

export const stats = [
  { value: 10, suffix: "+", label: "Premium Brands", description: "Authorized dealer for India's top brands" },
  { value: 100, suffix: "+", label: "Product Categories", description: "Comprehensive home hardware range" },
  { value: 25, suffix: "+", label: "Years of Trust", description: "Serving West Bengal since 1998" },
  { value: 5000, suffix: "+", label: "Happy Customers", description: "Across Siliguri and North Bengal" },
];

export const testimonials = [
  {
    id: 1,
    name: "Rajesh Agarwal",
    role: "Interior Designer, Siliguri",
    rating: 5,
    review: "RBC India is my go-to source for premium bathroom fittings. Their Jaquar range is always well-stocked and the team is incredibly knowledgeable. Quality products, fair pricing.",
    avatar: "RA",
  },
  {
    id: 2,
    name: "Priya Sharma",
    role: "Homeowner, Darjeeling",
    rating: 5,
    review: "Transformed our bathroom completely with products from RBC India. The chrome faucets and Jaquar shower head look absolutely stunning. Excellent after-sales service too.",
    avatar: "PS",
  },
  {
    id: 3,
    name: "Amit Bhattacharya",
    role: "Civil Contractor, Jalpaiguri",
    rating: 5,
    review: "For all my construction projects in North Bengal, RBC India is the most reliable supplier. Great product range, timely delivery, and they really understand quality.",
    avatar: "AB",
  },
  {
    id: 4,
    name: "Sunita Gupta",
    role: "Architect, Siliguri",
    rating: 5,
    review: "I've worked with many hardware distributors across West Bengal. RBC India stands out for their premium collection and authentic products. Highly recommended!",
    avatar: "SG",
  },
];

export const values = [
  {
    icon: "Shield",
    title: "100% Authentic Products",
    description: "Every product we carry is sourced directly from authorized manufacturers. No counterfeits, no compromises.",
  },
  {
    icon: "Star",
    title: "Premium Quality Range",
    description: "We partner only with India's most trusted brands — Jaquar, Racold, Sintex and more — so you get the best.",
  },
  {
    icon: "Users",
    title: "Expert Guidance",
    description: "Our experienced team helps you choose the right products for your project, budget, and aesthetic vision.",
  },
  {
    icon: "MapPin",
    title: "North Bengal's Favourite",
    description: "Based in Siliguri, we've been serving West Bengal's homes, hotels and construction projects since 1998.",
  },
];

export const contactInfo = {
  address: "Sevoke Road, Siliguri, West Bengal — 734001",
  addressFull: "Ramswarup Brothers and Co., Sevoke Road, Siliguri, West Bengal 734001, India",
  phone1: "+91 93825 45616",
  phone2: "(0353) 2777184",
  whatsapp: "919382545616",
  email: "info@rbcindia.in",
  hours: "Mon–Sat: 9:30 AM – 7:30 PM",
  mapUrl: "https://maps.google.com/?q=Siliguri,+West+Bengal",
};
